### ISSUE TITLE
Please describe how to reproduce the issue

### ISSUE THREAD

**Issue by EddyVerbruggen** [sokolovstas/demo-push-fail#1]
Hi,

Thanks for creating this repo to showcase an issue you experienced with the NativeScript Firebase plugin.

Please describe steps (and mention the platform) to reproduce the issue.

**Comment by sokolovstas** [comment]
Platform MacOS High Sierra

```
npm install
tns run android --bundle
```

Also I have seen strange errors on ios like FIRMessaging is undefined. But if I don't call register for push notifications push token is created only with addOnPushTokenReceivedCallback and addOnMessageReceivedCallback

**Comment by EddyVerbruggen** [comment]
I can't even start the app (with or without `--bundle`), because of these errors in `app.module`:

```
app/app.module.ts(13,40): error TS2307: Cannot find module 'oz'.
app/app.module.ts(14,29): error TS2307: Cannot find module 'web/core/data.service'.
app/app.module.ts(15,31): error TS2307: Cannot find module 'web/core/loader.service'.
app/app.module.ts(16,34): error TS2307: Cannot find module 'web/core/websocket.service'.
app/app.module.ts(17,32): error TS2307: Cannot find module 'web/message/service/message.service'.
app/app.module.ts(13,40): error TS2307: Cannot find module 'oz'.
app/app.module.ts(14,29): error TS2307: Cannot find module 'web/core/data.service'.
app/app.module.ts(15,31): error TS2307: Cannot find module 'web/core/loader.service'.
app/app.module.ts(16,34): error TS2307: Cannot find module 'web/core/websocket.service'.
app/app.module.ts(17,32): error TS2307: Cannot find module 'web/message/service/message.service'.
app/app.module.ts(18,29): error TS2307: Cannot find module 'web/user/user.service'.
app/app.module.ts(19,30): error TS2307: Cannot find module 'web/core/title.service'.
```

**Comment by sokolovstas** [comment]
Clean up code and imports from external dependicies

**Comment by sokolovstas** [comment]
On the latest version I cleaned up all platforms and run with syncAllFiles I see this:
JS: Failed to getCurrentPushToken: Uncomment firebase-messaging in the plugin's include.gradle first

But addOnPushTokenReceivedCallback and addOnMessageReceivedCallback works fine!

**Comment by sokolovstas** [comment]
In ios emulator, all handlers work fine but current push token return undefined. And I see error

CONSOLE ERROR file:///app/vendor.js:97075:30: Unhandled Promise rejection: Can't find variable: FIRMessaging ; Zone: <root> ; Task: null ; Value: ReferenceError: Can't find variable: FIRMessaging file:///app/vendor.js:101600:21

**Comment by sokolovstas** [comment]
In ios on the device I see the same error 
CONSOLE ERROR file:///app/vendor.js:97075:30: Unhandled Promise rejection: Can't find variable: FIRMessaging ; Zone: ; Task: null ; Value: ReferenceError: Can't find variable: FIRMessaging file:///app/vendor.js:101600:21

But push token is received via addOnPushTokenReceivedCallback and all works fine

**Comment by sokolovstas** [comment]
getCurrentPushToken produce errors on ios and android

**Comment by EddyVerbruggen** [comment]
Thanks for the update! I will look into this shortly.

**Comment by EddyVerbruggen** [comment]
The main issue is that you're using the plugin before the app starts. If all [this stuff](https://github.com/sokolovstas/demo-push-fail/blob/ed204a5c916b584c4461062bb445e62ab999932b/app/main.ts#L9-L34) would not be part of app.ts then I'm quite sure there wouldn't be an issue.

**Comment by sokolovstas** [comment]
> would not be part of main.ts then I'm quite sure there wouldn't be an issue.

And where I need to call this? In ngOnInit of application?

**Comment by EddyVerbruggen** [comment]
Good. I'll add the changes to the next version but still the advise is to wait until the app has started.
